### ISSUE TITLE
GeoKrety registration is broken

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#281]
It's not possible to register any GeoKrety since introduction of new map.

reported by Sentry:
```
Uncaught exception 'InvalidArgumentException' with message 'Expected integer value greater than or equals to 1 for geokretyId' in /var/www/html/lib/geokrety/service/ValidationService.php:29 Stack trace: #0 /var/www/html/lib/geokrety/service/TripService.php(91): Geokrety\Service\ValidationService->ensureIntGTE('geokretyId', NULL, 1) #1 /var/www/html/lib/geokrety/service/TripService.php(45): Geokrety\Service\TripService->getTripCacheId(NULL) #2 /var/www/html/lib/geokrety/service/TripService.php(56): Geokrety\Service\TripService->evictTripCache(NULL) #3 /var/www/html/konkret-mapka.php(12): Geokrety\Service\TripService->onTripUpdate(NULL) #4 /var/www/html/register.php(113): konkret_mapka(NULL) #5 {main} thrown
```

**Comment by kumy** [comment]
I'm rollbacking website to previous version 991bb03

**Comment by kumy** [comment]
Rollback effective on prod and staging

**Comment by kumy** [comment]
In order to reproduce, the checkbox "Set my home coordinates as a starting point." must be selected.

**Comment by kumy** [comment]
Fix deployed on staging and production.
