### ISSUE TITLE
"My recent logs" page: Exception when trying to sort by distance

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#384]
From @okainov in #4 
```
Uncaught exception 'Exception' with message ' prepare failed: (1052) Column 'droga' in order clause is ambiguous' in /var/www/html/lib/geokrety/repository/TripRepository.class.php:83
Stack trace:
#0 /var/www/html/lib/geokrety/repository/TripRepository.class.php(275): Geokrety\Repository\TripRepository-&gt;getBySql('SELECT    ru.ru...', 'd', Array)
#1 /var/www/html/mypage.php(84): Geokrety\Repository\TripRepository-&gt;getAllTripByAuthorId(26422, 'droga', 'desc', 25, 1)
#2 {main}
  thrown in <b>/var/www/html/lib/geokrety/repository/TripRepository.class.php</b> on line <b>83</b><br />
```

**Comment by kumy** [comment]
Fixed in `new-theme`. Closing.
